import {
  GET_ALL_ITEMS,
  GET_ITEM,
  UNSELECT_ITEM,
} from '../actions/ActionTypes';

const INITIAL_STATE = {
  allItems: [
    {
      "id": 1,
      "name": "ThunderDice",
      "link": "http://thunderdice.ws/",
      "logo": "https://pbs.twimg.com/profile_images/956587356693323776/s3zcO0iG_400x400.jpg",
      "summary": "Play SatoshiDice over the Lightning Network.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Back for even more FOMO. Win Bitcoin on the Lightning Network! Spam on Lightning, one hop at a time.",
      "tags": "Games",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Lastest",
      "temp_category": "Lastest",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 2,
      "name": "Zap",
      "link": "https://zap.jackmallers.com/",
      "logo": "https://camo.githubusercontent.com/5efa8dec3a741cccbc795b44999606285c659dc9/68747470733a2f2f696d6775722e636f6d2f73766e384a72772e6a7067",
      "summary": "Lightning wallet focused on user experience and ease of use.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Zap is a free Lightning Network wallet focused on user experience and ease of use, with the overall goal of helping the cryptocurrency community scale Bitcoin and other cryptocurrencies.",
      "tags": "Wallet",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Lastest",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 3,
      "name": "Lightning Desktop App",
      "link": "https://github.com/lightninglabs/lightning-app",
      "logo": "https://github.com/lightninglabs/lightning-app/raw/5f2620d1e99ed1372985fec2063066236e4c16d9/assets/screenshot.png",
      "summary": "An easy-to-use cross platform lightning wallet",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "An easy-to-use cross platform lightning wallet powered by lnd and developed by Lightning Labs.",
      "tags": "Wallet",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Lastest",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 4,
      "name": "HTLC.me",
      "link": "https://htlc.me",
      "logo": "local",
      "summary": "Hosted wallet great for quickly trying out Lightning payments on the Bitcoin testnet.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Lightning Network Custodial Wallet. Send and receive BTC on the Lightning Network.",
      "tags": "Wallet",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Concept",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 5,
      "name": "Bitrefill",
      "link": "https://en.bitrefill.com/south-korea/",
      "logo": "https://en.bitrefill.com/images/bitrefill_logo.svg",
      "summary": "Recharge prepaid phone cards with Bitcoin and Litecoin.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Bitrefill lets you top up any prepaid mobile phone using bitcoin. We support prepaid SIM cards from over 600 operators in over 160 countries. Full privacy and the top up happens as soon as the transaction clears.",
      "tags": "Merchant Service, Marketplace",
      "review_See_Eun": "",
      "review_Koji": "One of the first Lightning use cases. Hope we'll soon see a pay by second type of service using Lightning micropayments. That'll be pretty cool.",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 6,
      "name": "Coinmall",
      "link": "https://www.coinmall.com",
      "logo": "https://miro.medium.com/fit/c/240/240/1*7j_j4F6YcO0bsuszCtAlyA.png",
      "summary": "Buy & sell digital products with cryptocurrencies.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "The crypto marketplace for digital products where you can buy for Bitcoin. Product catagories can be found on the website.",
      "tags": "Marketplace",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 7,
      "name": "1ML",
      "link": "https://1ml.com",
      "logo": "https://1ml.com/images/logo.png",
      "summary": "Lightning Network Search and Analysis Engine.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Include node information, channels, services hosted on Lightning.",
      "tags": "Explorer",
      "review_See_Eun": "",
      "review_Koji": "My favorite Lightning explorer at the moment. Helping me catch up with the latest state of the Lightning node and channel states( and they are growing fast)",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 8,
      "name": "WooCommerce Gateway Plugin for Lightning (LND)",
      "link": "https://github.com/joaodealmeida/woocommerce-gateway-lightning",
      "logo": "https://camo.githubusercontent.com/840ec7f35533cc95d78e555b73a692a81d369fac/68747470733a2f2f692e696d6775722e636f6d2f516257696b73312e706e67",
      "summary": "Gateway plugin to accept Lightning payments at WooCommerce stores, built on LND.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "WooCommerce is the most customizable eCommerce platform for building online businesses. Now WooCommerce stores can accept any and all Lightning payments.",
      "tags": "Merchant Service",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "c-Lightning Lapps"
    },
    {
      "id": 9,
      "name": "WooCommerce Gateway Plugin for Lightning (Lightning Charge)",
      "link": "https://github.com/ElementsProject/woocommerce-gateway-lightning",
      "logo": "https://camo.githubusercontent.com/449fdf451cadfa198cf7bf2772d1152c32d78197/68747470733a2f2f692e696d6775722e636f6d2f51363779356c322e706e67",
      "summary": "Gateway plugin to accept Lightning payments at WooCommerce stores, based on Lightning Charge.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "WooCommerce is the most customizable eCommerce platform for building online businesses. Now WooCommerce stores can accept any and all Lightning payments.",
      "tags": "Merchant Service",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 10,
      "name": "LND Explorer",
      "link": "https://demo1.lndexplorer.com",
      "logo": "https://demo1.lndexplorer.com/public/lnd-explorer.png",
      "summary": "A web interface for LND.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "LND Explorer is a web interface for interacting with the Lightning Network via LND. Think block explorers about Lightning's layer 2.",
      "tags": "Explorer",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 11,
      "name": "Lnd Web Client",
      "link": "https://github.com/mably/lncli-web",
      "logo": "https://i.imgur.com/wM4OJWk.png",
      "summary": "A lightweight web client for LND.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Light-weight web client for the lnd daemon written in NodeJS / Angular.",
      "tags": "Explorer, Wallet",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 12,
      "name": "Lightning Network Daemon",
      "link": "https://github.com/lightningnetwork/lnd",
      "logo": "https://raw.githubusercontent.com/lightningnetwork/lnd/master/logo.png",
      "summary": "A complete implementation of a Lightning Network node.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "The most advanced and most developer-friendly implementation of the Lightning Network protocol. lnd provides superior reliability, interoperability and security for the next generation of global-scale financial applications.",
      "tags": "Implementation, Wallet",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 13,
      "name": "Y'alls",
      "link": "https://yalls.org",
      "logo": "local",
      "summary": "Read and write articles, with Lightning Network micropayments.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "A Lightning Network version of Yours.org. Write articles, question and answer, form a group and make payment with the Lightning Network.",
      "tags": "Media, Tipping",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Concept",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 14,
      "name": "LNCast",
      "link": "https://lncast.com",
      "logo": "https://pbs.twimg.com/profile_images/961286858335399938/8CssEWkM_400x400.jpg",
      "summary": "Podcatcher using micropayments on the Lightning Network.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "LNCast is a podcatcher that allows creators to monetize their podcasts using micropayments on the Lightning Network. While being focused on podcasts, LNCast is a proof of concept for a broader idea: mircropayments in exchange for data.",
      "tags": "Media, Tipping",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 15,
      "name": "ZigZag",
      "link": "https://zigzag.bitlum.io/#/",
      "logo": "local",
      "summary": "Exchange Top\nCryptocurrencies\nin seconds\nwith low fees",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "ZigZag enables 10 second asset exchanges with no user registration required, and avoids the typical high blockchain fees by leveraging the power of payment channels.",
      "tags": "Exchange",
      "review_See_Eun": "",
      "review_Koji": "Evolution of ShapeShift so-to-speak. It shows that, by leveraging Lightning Network, current cyprto services can benefit immediately, allowing users to avoid the high on-chain fees and slow confirmation time.",
      "rating": "",
      "category": "Editor",
      "temp_category": "Editor",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 16,
      "name": "lnd.fun",
      "link": "http://lnd.fun",
      "logo": "local",
      "summary": "Panel for webmasters to manage their full lightning node.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "A panel with Graphic User Interface for webmasters to manage their full lightning node. Displays all sorts of information about all the activity happening on the Lightning Network.",
      "tags": "Explorer",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Concept",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 17,
      "name": "LightningJ",
      "link": "http://www.lightningj.org",
      "logo": "",
      "summary": "Lightning APIs for Java.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "A project intending to simplify the integration of Lightning implementations for Java developers, containing simple to use API implementations and converters between JSON and XML.",
      "tags": "Developer Tools",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Concept",
      "temp_category": "Concept",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 18,
      "name": "Lightning Spin",
      "link": "https://www.lightningspin.com/",
      "logo": "local",
      "summary": "A Bitcoin spinner game which lives on top of the Lightning Network.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Lightning Spin is a bitcoin gambling game that lives on top of the Lightning Network. It's a simple yet exciting game - enter your wager, select a multiplier and spin the wheel. If the wheel lands on your target multiplier, you win!",
      "tags": "Games",
      "review_See_Eun": "",
      "review_Koji": "One of the best looking Lightning gamble services at the moment.  But I'm hoping it will improve the error handling for withdrawals. Some of my Satoshis are stuck somewhere and I couldn't retrieve them. (Make sure to use the wallet that lets you receive the LN payment)",
      "rating": "",
      "category": "Editor",
      "temp_category": "Editor",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 19,
      "name": "Ifpaytt",
      "link": "https://github.com/ElementsProject/ifpaytt",
      "logo": "https://blockstream.com/images/blog/week-of-lapps/lightning-ifpaytt-banner.png",
      "summary": "If Pay Then That - use Bitcoin Lightning payments to trigger If This Then That actions.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Allows users to create applets by combining triggers and actions. The payment of a Lightning Network invoice becomes a trigger and when it’s completed, the programmatic action occurs; a user simply has to create an IFTTT applet linking them together.",
      "tags": "Developer Tools",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "c-Lightning Lapps"
    },
    {
      "id": 20,
      "name": "LightningTip",
      "link": "https://github.com/michael1011/lightningtip",
      "logo": "https://camo.githubusercontent.com/080d89e815255b38ced9501c99fb446e1c0cdc4c/68747470733a2f2f692e696d6775722e636f6d2f306d4f456754662e676966",
      "summary": "Get tips via the Lightning Network.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "A simple way to accept tips via the Lightning Network on your website.",
      "tags": "Tipping",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 21,
      "name": "In-tip-slack",
      "link": "https://github.com/CryptoFR/ln-tip-slack",
      "logo": "",
      "summary": "Slack tipping bot using Bitcoin Lightning Network for payments.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Show appreciation for each other through a slack tipping bot using Bitcoin Lightning Network for payments.",
      "tags": "Tipping",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Concept",
      "temp_category": "Concept",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 22,
      "name": "Cointippy",
      "link": "https://www.cointippy.com",
      "logo": "https://www.cointippy.com/img/cointippy.png",
      "summary": "Custodial tip bot available on multiple platforms, including Reddit, Twitter, and Telegram.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Content rewarding service for Reddit, Twitter, Telegram, and Twitch with cryptocurrency. Powered by CoinMall.com.",
      "tags": "Tipping, Media",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 23,
      "name": "Hammercoin",
      "link": "https://hammerco.in",
      "logo": "http://press.mego.cl/hammercoin/images/102-market.png",
      "summary": "A MMORPG using Lightning for in-game payments.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Hammercoin is a multiplayer game with fast hack-n-slash style gameplay. The game is denominated in Bits (a tiny fraction of a Bitcoin), so players can buy or sell game items using cryptocurrency. There's also rewards for the best players who complete weekly events and quests.",
      "tags": "Games",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 24,
      "name": "Bitquest",
      "link": "http://bitquest.co",
      "logo": "http://bitquest.co/images/bitquest-logo.png",
      "summary": "The first Minecraft server denominated in cryptocurrency.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "A crypto-centric Minecraft server with its own Lightning payments option.",
      "tags": "Games",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 25,
      "name": "Lightning Gem",
      "link": "https://lightninggem.com",
      "logo": "https://lightninggem.com/img/gem.png",
      "summary": "The original and most popular bitcoin chain game - now with lightning. Anyone can play for fun, profit, and advertising.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "The Lightning Gem is a fun game of speculation where anyone can win bitcoins. It is a remake and continuation of the original Bitcoin Gem. It runs on the bitcoin lightning network and uses lnd for lightning functionality.",
      "tags": "Games",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 26,
      "name": "Eclair",
      "link": "https://github.com/ACINQ/eclair",
      "logo": "https://raw.githubusercontent.com/ACINQ/eclair/master/.readme/logo.png",
      "summary": "Scala implementation of the Lightning Network.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Eclair Wallet is a next generation, Lightning-ready Bitcoin wallet developed by ACINQ. It can be used as a regular Bitcoin wallet, and can also connect to the Lightning Network for cheap and instant payments.",
      "tags": "Implementation, Wallet",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "Eclair Lapps"
    },
    {
      "id": 27,
      "name": "Starblocks",
      "link": "https://starblocks.acinq.co/#/",
      "logo": "https://starblocks.acinq.co/static/images/logo_starblocks.png",
      "summary": "Virtual coffee shop based on Eclair.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Website powered by Eclair where one can buy Starbucks coffee using the Lightning Network.",
      "tags": "Marketplace",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "Eclair Lapps"
    },
    {
      "id": 28,
      "name": "Strike",
      "link": "https://strike.acinq.co/#/",
      "logo": "https://strike.acinq.co/static/images/strike_built_hz_white.png",
      "summary": "Bitcoin payment channel for businesses powered by ACINQ.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Strike is an easy to use, stripe®-like API for Lightning. Let us handle your Lightning payments, and receive aggregated bitcoin transactions every week, day, or hour! A user-friendly dashboard allows you to monitor your payments in real time.",
      "tags": "Merchant Service",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "Eclair Lapps"
    },
    {
      "id": 29,
      "name": "Lightning Conductor",
      "link": "https://lightningconductor.net",
      "logo": "local",
      "summary": "Lightning <-> Bitcoin converter.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "We are an organisation that is striving to provide real services to real businesses selling real stuff using the Lightning Network. We are aim to become a trusted partner to those businesses. Convert Lightning to Bitcoin and Bitcoin to Lightning.",
      "tags": "Merchant Service",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Concept",
      "lightningapps.io": "o",
      "lightningapps.io category": "Eclair Lapps"
    },
    {
      "id": 30,
      "name": "Blockstream Store",
      "link": "https://store.blockstream.com",
      "logo": "https://storage.googleapis.com/lightning-store-media/uploads/2018/01/blockstream-logo.png",
      "summary": "Bitcoin paraphernalia that can only be purchased over LN.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Bitcoin Lightning store by Blockstream powered by Lightning Charge and the WooCommerce Lightning Gateway.",
      "tags": "Marketplace",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "c-Lightning Lapps"
    },
    {
      "id": 31,
      "name": "Lightning Charge",
      "link": "https://github.com/ElementsProject/lightning-charge",
      "logo": "local",
      "summary": "A drop-in solution for accepting lightning payments.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "A drop-in solution for accepting lightning payments, built on top of c-lightning with radically low fees, nano payments, and instant confirmations. Many Lapps are built on top of this API.",
      "tags": "Merchant Service",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Concept",
      "lightningapps.io": "o",
      "lightningapps.io category": "c-Lightning Lapps"
    },
    {
      "id": 32,
      "name": "Nanopos",
      "link": "https://github.com/ElementsProject/nanopos",
      "logo": "https://camo.githubusercontent.com/7dec1bc492e0dbef6325f770e2d9bfb9d69fe149/68747470733a2f2f692e696d6775722e636f6d2f7075736c594b622e706e67",
      "summary": "A simple Lightning point-of-sale system with a clean & minimal web UI using Lightning Charge.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "A simple Lightning point-of-sale system with a clean & minimal web UI. Optimized for places selling fixed-price items, but also has an option for billing custom amounts. A small codebase and a great starting point for developing your own Lightning Charge apps!",
      "tags": "Merchant Service",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "c-Lightning Lapps"
    },
    {
      "id": 33,
      "name": "Filebazzar",
      "link": "https://github.com/ElementsProject/filebazaar",
      "logo": "https://camo.githubusercontent.com/6b9be98b656db39e51cbd4b9b44a8aca61fcec08/68747470733a2f2f692e696d6775722e636f6d2f556851443054672e676966",
      "summary": "Sell digital files with Bitcoin & Lightning.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "An ecommerce tool for content creators to sell digital files with Bitcoin & Lightning with a simple setup and minimal configuration, just put some files in a directory and start the server. Lightweight web browsing interface, works without JavaScript. Generates previews for images, videos, audio, pdf and text documents.",
      "tags": "Merchant Service",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 34,
      "name": "Lightning Publisher for WordPress",
      "link": "https://github.com/ElementsProject/wordpress-lightning-publisher",
      "logo": "https://camo.githubusercontent.com/43ab6a383d0688e60c5d14fd7c6bb37a35bf07ab/68747470733a2f2f692e696d6775722e636f6d2f786146536134452e676966",
      "summary": "A patronage model for unlocking WordPress blog entries.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Lightning Publisher for WordPress allows you to offer previews of your blog posts and require a Lightning Network payment to release the rest. A plug-in that can turn anyone into their own publisher by allowing them to collect payments when they share their writing or other blog content on a WordPress system.",
      "tags": "Merchant Service",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "c-Lightning Lapps"
    },
    {
      "id": 35,
      "name": "Paypercall",
      "link": "https://github.com/ElementsProject/paypercall",
      "logo": "https://www.blockstream.com/images/blog/week-of-lapps/lightning-paypercall-banner.png",
      "summary": "A programmer’s toolkit for Lightning that enables micropayments for individual API calls.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Charge for HTTP APIs on a pay-per-call basis with Bitcoin and Lightning. Want to require a payment when users take some programmatic action, such as sending an SMS or running imaging processing? That's what paypercall is for.",
      "tags": "Developer Tools",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "c-Lightning Lapps"
    },
    {
      "id": 36,
      "name": "Lightning Jukebox",
      "link": "https://github.com/ElementsProject/lightning-jukebox",
      "logo": "https://camo.githubusercontent.com/a8133cedbccc35e3a0b6d25cf5f9f4dd790e521c/68747470733a2f2f692e696d6775722e636f6d2f48396b464451572e706e67",
      "summary": "A Lightning powered Jukebox. Pay with Bitcoin to choose your music from YouTube.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "The Lightning Jukebox is a video jukebox that enables users to request songs (or videos) for a micropayment. It does so by linking YouTube videos to a Lightning Charge powered payment system.",
      "tags": "Merchant Service, Media",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "c-Lightning Lapps"
    },
    {
      "id": 37,
      "name": "Nanotip",
      "link": "https://github.com/ElementsProject/nanotip",
      "logo": "https://camo.githubusercontent.com/ba7ef9e2fd1bff473428478de359b7d843e46777/68747470733a2f2f692e696d6775722e636f6d2f574c6f695254322e676966",
      "summary": "A simple web server for accepting lightning donations.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Nanotip solves Lightning’s problem for tipping by creating a simple web server that writes Lightning payment requests on the fly. It gives each content provider their own tip-bot in a way that keeps those creators in total control, while giving them stronger privacy than a classic Bitcoin tipjar.",
      "tags": "Merchant Service, Tipping",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "c-Lightning Lapps"
    },
    {
      "id": 38,
      "name": "BitcoinLightning.shop",
      "link": "https://bitcoinlightning.shop",
      "logo": "local",
      "summary": "Shop to pay with Lightning.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Shop with Bitcoin Lightning, built on BTCPay and the c-lightning WooCommerce Plugin.",
      "tags": "Marketplace",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Concept",
      "lightningapps.io": "o",
      "lightningapps.io category": "c-Lightning Lapps"
    },
    {
      "id": 39,
      "name": "Lightning Ramp",
      "link": "https://www.lightningramp.com/",
      "logo": "https://pbs.twimg.com/profile_images/963215649282469889/BpdTRGqH_400x400.jpg",
      "summary": "Fund Lightning Ramp via exchanges, enter the destination address, and Lightning Ramp handles the rest to securely deliver the payment to the destination address.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Connecting cryptocurrency exchanges to the Lightning Network. In the most current version of Lightning Ramp, Coinbase is integrated. Future releases will integrate with other popular exchanges to allow for a complete freeflow of digital currency.",
      "tags": "Merchant Service, Exchange",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 40,
      "name": "SwiftLightning",
      "link": "https://swiftlightning.io/",
      "logo": "https://camo.githubusercontent.com/9c89a11d06294d11a9018892a7399f21666a82eb/68747470733a2f2f7777772e73776966746c696768746e696e672e696f2f696d672f53776966744c696768746e696e6750726f6a6563742e706e67",
      "summary": "A Lightning Network light wallet implementation on native iOS using Swift.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "SwiftLightning is a Lightning Network light wallet implementation based on the open sourced Lightning Network Daemon. This project is written for iOS. By being an early implementation of a mobile Lighting wallet, it is hoped that SwiftLightning can act as a test harness to help accelerate LND's features and reliability for iOS.",
      "tags": "Implementation, Wallet",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "o",
      "lightningapps.io category": "LND Lapps"
    },
    {
      "id": 41,
      "name": "c-lightning",
      "link": "https://github.com/ElementsProject/lightning",
      "logo": "local",
      "summary": "A Lightning Network implementation in C.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "c-lightning is a standard compliant implementation of the Lightning Network protocol. The Lightning Network is a scalability solution for Bitcoin, enabling secure and instant transfer of funds between any two parties for any amount.",
      "tags": "Implementation",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Concept",
      "lightningapps.io": "o",
      "lightningapps.io category": "c-Lightning Lapps"
    },
    {
      "id": 42,
      "name": "Jellybean",
      "link": "https://github.com/elaineo/Jellybean",
      "logo": "https://i0.wp.com/elaineou.com/wp-content/uploads/2018/03/beans4bits.png",
      "summary": "Lightning-powered vending machine on Raspberry Pi.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Create your own vending machine using the Lightning Network and a Raspberry Pi you have lying around the house! Jellybeans and other candy not included but suggested.",
      "tags": "Merchant Service",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 43,
      "name": "Lightning Twitter Bot",
      "link": "https://github.com/elaineo/lightningbot",
      "logo": "https://i2.wp.com/elaineou.com/wp-content/uploads/2018/01/Screen-Shot-2018-01-19-at-9.29.24-PM.png",
      "summary": "Bitcoin-payable Twitter bot with Lightning Charge.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Buy tweets from your bot using Lightning! Wordpress meets WooCommerce and Lightning Payments plugins.",
      "tags": "Merchant Service, Marketplace",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 44,
      "name": "LightningBuddy",
      "link": "https://github.com/elaineo/LightningBuddy",
      "logo": "https://raw.githubusercontent.com/elaineo/LightningBuddy/master/docs/pay.png",
      "summary": "Twitter relay for Lightning JSON-RPC interface.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "LightningBuddy is a library that can be used to talk to a lightning node from a Twitter account. It can be used to send lightning-payable messages for Twitter bots, tipping, or other applications.",
      "tags": "Merchant Service, Tipping, Developer Tools",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 45,
      "name": "Neutrino",
      "link": "https://github.com/lightninglabs/neutrino",
      "logo": "",
      "summary": "Neutrino is an experimenta privacy-preserving Bitcoin light client and designed with mobile Lightning Network clients in mind.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "An open platform developed by Lightning Labs that enables users with mobile devices to conduct blockchain and Lightning Network transactions quickly and easily. Neutrino provides “light clients” with security and privacy that weren’t available with previous light client concepts.",
      "tags": "Implementation, Wallet",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Concept",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 46,
      "name": "Submarine Swap",
      "link": "http://submarineswaps.org/",
      "logo": "",
      "summary": "Trade on-chain tokens for Lightning invoice payments.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Submarine swaps exchange off-chain Lightning tokens for on-chain tokens, using a simple HTLC to help with atomicity.",
      "tags": "Exchange, Developer Tools",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Concept",
      "temp_category": "Concept",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 47,
      "name": "Lightning Wallet",
      "link": "http://lightning-wallet.com/",
      "logo": "https://lh3.googleusercontent.com/NFw07FRGSMQiCa1qjh8MnUYrOnmZWyMbXr-gL_Rk-3PhwCajQSbalkzDmcovvTPxFMc=s360-rw",
      "summary": "A wallet which features a standalone SPV Bitcoin node with a fully functional built-in Lightning node.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Android Lightning Wallet using the ACINQ/Eclair implementation. This project uses a special monetized backend service \"Olympus\" providing fiat prices and other wallet services.",
      "tags": "Wallet, Implementation",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 48,
      "name": "Rawtx",
      "link": "https://rawtx.com/",
      "logo": "https://camo.githubusercontent.com/9a31ce57434ffa8729169d451021e5c142fa4629/68747470733a2f2f72617774782e636f6d2f6173736574732f616e64726f69642d6170702d73637265656e73686f742e706e67",
      "summary": "A mobile lightning network wallet.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Rawtx is an open-source lightning network wallet powered by lnd which allows you to send and receive Bitcoins both on blockchain and lightning network.",
      "tags": "Wallet",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 49,
      "name": "CoinClip",
      "link": "https://itunes.apple.com/us/app/coinclip-testnet/id1372927440?ls=1&mt=8",
      "logo": "https://is5-ssl.mzstatic.com/image/thumb/Purple125/v4/6c/12/77/6c12779d-8375-924f-b9c5-aff860c926d0/AppIcon-1x_U007emarketing-85-220-0-6.png/1200x630wa.jpg",
      "summary": "BTC Lightning Wallet on Testnet.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Send Bitcoin via the Lightning Network on iOS. Also works as an on chain wallet to send and receive regular Bitcoin transactions. Open a channel to start using the Lightning Network.",
      "tags": "Wallet",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 50,
      "name": "Union7 LND Thin Wallet",
      "link": "https://www.lndthinwallet.com/",
      "logo": "https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/be/d1/33/bed13382-90c9-e6b4-0879-770b8ccd455b/pr_source.png/690x0w.jpg",
      "summary": "LND Thin Wallet is a simple, thin mainnet Lightning client that lets you send and receive Bitcoins privately and instantly from your mobile device by connecting to an LND node you are running on another device.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Send and receive Bitcoin privately and instantly from your mobile device with this simple, \"thin\" Lightning wallet, which connects to an LND node you are running on another device. In addition to allowing you to send and receive Bitcoin over the Lightning network, this app allows you to view transaction and channel details, open up new channels, and deposit Bitcoin to your Lightning wallet.",
      "tags": "Wallet",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 51,
      "name": "Billfodl",
      "link": "https://billfodl.com/",
      "logo": "https://cdn.shopify.com/s/files/1/2634/0984/files/billfodl_black_1b2f5b7a-9b82-42e5-b620-4075025570da_360x.png",
      "summary": "Buy a stainless steel crypto wallet using Lightning.",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "Wallet with the best corrosion resistance in the stainless family to protect your information in even the saltiest environments. And, it’s impervious to any type of electrical hazard you could dream of. Now even better with Lightning payments.",
      "tags": "Marketplace",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Latest",
      "temp_category": "Latest",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 52,
      "name": "Poketoshi",
      "link": "https://poketoshi.com/",
      "logo": "",
      "summary": "",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "",
      "tags": "",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "Editor",
      "temp_category": "Concept",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 53,
      "name": "Satoshi's Place",
      "link": "https://satoshis.place/",
      "logo": "",
      "summary": "",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "",
      "tags": "",
      "review_See_Eun": "",
      "review_Koji": "Probably the first Lapp to get me thinking of a potential of Lightning's micropayment beyond simple payment. And of course the shared board would become a huge mess but it's a part of the fun...",
      "rating": "",
      "category": "Editor",
      "temp_category": "Concept",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 54,
      "name": "OpenNode",
      "link": "https://opennode.co/",
      "logo": "",
      "summary": "",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "",
      "tags": "",
      "review_See_Eun": "",
      "review_Koji": "Making Lightning Network so much easier to start with. One of more user friendly looking Lapps at the moment.",
      "rating": "",
      "category": "Editor",
      "temp_category": "Concept",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 55,
      "name": "BTCPay",
      "link": "https://btcpay-server-testnet.azurewebsites.net/",
      "logo": "",
      "summary": "",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "",
      "tags": "",
      "review_See_Eun": "",
      "review_Koji": "One click deploy of LND and C-lightning to Azure. And it's all open source. Cannot appreciate the dev and community's effort enough.",
      "rating": "",
      "category": "Editor",
      "temp_category": "Concept",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 56,
      "name": "Proof of Hat",
      "link": "https://www.excellion.com/?ref=tokendaily",
      "logo": "",
      "summary": "",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "",
      "tags": "",
      "review_See_Eun": "",
      "review_Koji": "A hat is the first step on the path to self-discovery\" Samson Mow... Okay, really? lol At least it's the only place so far where you can buy Bitcoin hats with Lightning.",
      "rating": "",
      "category": "Editor",
      "temp_category": "Concept",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    },
    {
      "id": 57,
      "name": "Amoveo",
      "link": "",
      "logo": "",
      "summary": "A blockchain for trust-free markets in financial derivatives",
      "Bigger Logo Thumbnail": "",
      "Screenshot": "",
      "description": "",
      "tags": "",
      "review_See_Eun": "",
      "review_Koji": "",
      "rating": "",
      "category": "",
      "temp_category": "Concept",
      "lightningapps.io": "",
      "lightningapps.io category": ""
    }
  ],
  selectedItem: null,
};

export default (state = INITIAL_STATE, action) => {
  switch (action.type) {
    case GET_ALL_ITEMS:
      return {
        ...state,
      };
    case GET_ITEM:
      const selectedItem = state.allItems.find(item => item.name === action.payload)
      return {
        ...state,
        selectedItem,
      };
    case UNSELECT_ITEM:
      return {
        ...state,
        selectedItem: null,
      };
    default:
      return state;
  }
};
